services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: tasklist_container
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db_tasklist
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
